/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Protected, ProtectedInterface } from "../../contracts/Protected";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract Authorization",
        name: "_authorization",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50604051610167380380610167833981810160405281019061003291906100ed565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505061011a565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100a88261007d565b9050919050565b60006100ba8261009d565b9050919050565b6100ca816100af565b81146100d557600080fd5b50565b6000815190506100e7816100c1565b92915050565b60006020828403121561010357610102610078565b5b6000610111848285016100d8565b91505092915050565b603f806101286000396000f3fe6080604052600080fdfea26469706673582212206ad71eb1e345dd6ee3ffd8f2f738b50877dbf111e82ae1d066234ee8e517d62764736f6c63430008080033";

type ProtectedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ProtectedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Protected__factory extends ContractFactory {
  constructor(...args: ProtectedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _authorization: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Protected> {
    return super.deploy(_authorization, overrides || {}) as Promise<Protected>;
  }
  override getDeployTransaction(
    _authorization: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_authorization, overrides || {});
  }
  override attach(address: string): Protected {
    return super.attach(address) as Protected;
  }
  override connect(signer: Signer): Protected__factory {
    return super.connect(signer) as Protected__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ProtectedInterface {
    return new utils.Interface(_abi) as ProtectedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Protected {
    return new Contract(address, _abi, signerOrProvider) as Protected;
  }
}
